version: "3"

services:
  database:
    image: mobystore_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD: gordonpassword
      POSTGRES_DB: mobystore
    networks:
     - back-tier

  appserver:
    image: mobystore_app
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  front-tier:
  back-tier: